swagger: "2.0"
info: 
  description: Spaten Education Server API
  version: 1.0.0
  title: Contracts Server API
host: localhost
basePath: /api
schemes:
  - http
tags:
- name: login
  description: Login user
- name: user
  description: User related endpoints
- name: roadmap
  description: Roadmap operations
- name: achievements
  description: User achievements

paths:
  /login:
    post:
      tags:
      - login
      summary: Login user to the app
      description: Logins existing user or creates a new one. Returns a user information. For a new user will send a set of questions
      # security:
      #   - Bearer: []
      produces:
      - application/json
      parameters:
      - in: body
        name: login
        schema:
          $ref: "#/definitions/RequestLogin"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/ResponseLogin"
        400:
          description: bad request
        403:
          description: forbidden
        500:
          description: internal error

  /user/{id}:
    get:
      tags:
      - user
      summary: Get user information
      description: Returns a user information
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: Numeric ID of the user to get
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/ResponseUser"
        400:
          description: bad request
        404:
          description: not found
        500:
          description: internal error

  /user/{id}/process-poll:
    post:
      tags:
      - user
      summary: Process user poll answers
      description: Returns generated roadmap
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: Numeric ID of the user
      - in: body
        name: poll
        schema:
          $ref: "#/definitions/RequestPoll"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/ResponsePollProcess"
        400:
          description: bad request
        404:
          description: not found
        500:
          description: internal error

  /roadmap/{id}:
    get:
      tags:
      - roadmap
      summary: Get roadmap
      description: Returns existing roadmap
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: Numeric ID of the user
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/ResponsePoll"
        404:
          description: not found
        500:
          description: internal error

        
        

definitions:
  RequestLogin:
    type: object
    required:
    - login
    - password
    properties:
      login:
        type: string
      password:
        type: string

  RequestPoll:
    type: object
    required:
    - answers-first
    - answers-second
    properties:
      answers-first:
        $ref: "#/definitions/AnswerMap"
      answers-second:
        $ref: "#/definitions/AnswerMap"

  AnswerMap:
    type: object
    additionalProperties:
      type: array
      items:
        type: integer

  ResponseLogin:
    type: object
    required:
      - user
      - new
    properties:
      user:
        $ref: "#/definitions/ResponseUser"
      new:
        type: boolean
      first-poll:
        type: array
        items:
          $ref: "#/definitions/ResponsePoll"
      second-poll:
        type: array
        items:
          $ref: "#/definitions/ResponsePoll"

  ResponseUser:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      roadmap-ids:
        type: array
        items:
          type: integer
      badge-ids:
        type: array
        items:
          type: integer
      certificate-ids:
        type: array
        items:
          type: integer

  ResponsePoll:
    type: object
    required:
      - id
      - description
      - questions
    properties:
      id:
        type: string
      description:
        type: string
      questions:
        type: array
        items:
          $ref: "#/definitions/ResponseQuestion"

  ResponseQuestion:
    type: object
    required:
      - id
      - description
      - answers
    properties:
      id:
        type: string
      description:
        type: string
      answers:
        type: array
        items:
          $ref: "#/definitions/ResponseAnswer"

  ResponseAnswer:
    type: object
    required:
      - id
      - description
    properties:
      id:
        type: string
      description:
        type: string

  ResponsePollProcess:
    type: object
    required:
      - roadmap-id
    properties:
      roadmap-id:
        type: integer

